# Generated by Django 4.0.3 on 2022-04-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travels',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='travels',
            name='start_time',
        ),
        migrations.AddField(
            model_name='travels',
            name='end_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travels',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
