# Generated by Django 4.0.3 on 2022-04-06 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_remove_travels_end_time_remove_travels_start_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travels',
            old_name='end_data',
            new_name='end_date',
        ),
    ]
