# Generated by Django 4.0.3 on 2022-04-11 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_remove_travels_bus_remove_travels_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelsschedule',
            name='travel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel', to='travels.travels', verbose_name='Trayecto'),
        ),
    ]
