# Generated by Django 4.0.3 on 2022-04-14 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_alter_buses_number'),
        ('drivers', '0001_initial'),
        ('travels', '0005_travelsschedule_travel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelsschedule',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bus_travels', to='bus.buses', verbose_name='Autobus'),
        ),
        migrations.AlterField(
            model_name='travelsschedule',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travels', to='drivers.drivers', verbose_name='Conductor'),
        ),
        migrations.AlterField(
            model_name='travelsschedule',
            name='travel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_schedules', to='travels.travels', verbose_name='Trayecto'),
        ),
    ]
