# Generated by Django 4.0.3 on 2022-04-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('age', models.PositiveIntegerField(verbose_name='Edad')),
                ('cel_phone', models.CharField(max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
            },
        ),
    ]
