# Generated by Django 4.0.3 on 2022-04-03 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('age', models.PositiveIntegerField(verbose_name='Edad')),
                ('seat_number', models.PositiveIntegerField(default=10, verbose_name='Número de asiento')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seatings', to='travels.travels', verbose_name='Trayecto')),
            ],
            options={
                'verbose_name': 'Asiento',
                'verbose_name_plural': 'Asientos',
            },
        ),
    ]
