# Generated by Django 4.0.3 on 2022-04-11 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seatings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatings',
            name='travel',
        ),
    ]
