# Generated by Django 4.0.3 on 2022-04-11 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_remove_travels_bus_remove_travels_driver_and_more'),
        ('seatings', '0002_remove_seatings_travel'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatings',
            name='travel_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seatings', to='travels.travelsschedule', verbose_name='Trayecto'),
        ),
    ]
